pipeline {
  agent { label 'master' }

  stages {
    stage('Clean WorkSpace') {
      steps {
        sh 'echo -e "\033[0;34m## Limpando o Workspace  ##\033[0m"'
        deleteDir()
      }
    }

    stage('git clone fiscal-xml-consult') {
      steps{
          sh 'echo -e "\033[0;34m## Clonando repositório fiscal-xml-consult ##\033[0m"'
          checkout([
            $class: 'GitSCM',
            extensions: [
              [$class: 'CleanCheckout'],
            ],
            branches: [
              [name: 'master']
            ],
            userRemoteConfigs:
              [[
                credentialsId: '',
                url: 'https://github.com/ligado/hello-world-servlet.git'
              ]]
            ])
         }
      }

    stage('Build da aplicação') {
      steps {
        sh 'echo -e "\033[0;33m## Build ##\033[0m"'
          sh '''
             mvn clean install
             '''
        }
      }

    stage('Disponibilizando artefato para Download') {
        steps {
          sh 'echo -e "\033[0;34m## Archiving artifacts  ##\033[0m"'
          archiveArtifacts artifacts: 'f**/target/*.war', fingerprint: true
          }
        }

    stage('Disponibilizando report Junit') {
        steps {
          sh 'echo -e "\033[0;34m## Junit report ##\033[0m"'
          junit allowEmptyResults: true, testDataPublishers: [[$class: 'AttachmentPublisher']], testResults: '**/target/surefire-reports/*.xml'
          }
        }
      }
    }
